#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dc27

include $(IDF_PATH)/make/project.mk

CFLAGS+=-DESP32 -DATCA_HAL_I2C -DATCA_PRINTF 

#size:
#	xtensa-esp32-elf-size build/dc26esp.elf


