#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dc27

include $(IDF_PATH)/make/project.mk

#size:
#	xtensa-esp32-elf-size build/dc26esp.elf


