#ifndef DEVKIT_DEFS
#define DEVKIT_DEFS

//#define ESP32_WROOM

#ifdef ESP32_WROOM
#define UP_BUTTON   GPIO_NUM_15
#define DOWN_BUTTON GPIO_NUM_14
#define FIRE_BUTTON GPIO_NUM_0

#define UP_GPIO_INPUT   (1ULL << GPIO_NUM_15)
#define DOWN_GPIO_INPUT (1ULL << GPIO_NUM_14)
#define FIRE_GPIO_INPUT (1ULL << GPIO_NUM_0)

#define I2C_SCL NOPIN
#define I2C_SDA NOPIN
#define I2C_SCL2 NOPIN
#define I2C_SDA2 NOPIN

#define PIN_NUM_TOUCH_CLK  GPIO_NUM_26
#define PIN_NUM_TOUCH_CS   GPIO_NUM_27
#define PIN_NUM_TOUCH_IRQ  GPIO_NUM_32
#define PIN_NUM_TOUCH_MISO GPIO_NUM_35
#define PIN_NUM_TOUCH_MOSI GPIO_NUM_33

#define PIN_NUM_DISPLAY_RESET     GPIO_NUM_18
#define PIN_NUM_DISPLAY_CLK       GPIO_NUM_19
#define PIN_NUM_DISPLAY_DATA_CMD  GPIO_NUM_21
#define PIN_NUM_DISPLAY_CS        GPIO_NUM_22
#define PIN_NUM_DISPLAY_MOSI      GPIO_NUM_23
#define PIN_NUM_DISPLAY_MISO      GPIO_NUM_25
#define PIN_NUM_DISPLAY_BACKLIGHT GPIO_NUM_5

#define PAIRING_UART UART_NUM_2
#define PAIRING_RX   GPIO_NUM_16
#define PAIRING_TX   GPIO_NUM_17
#define PAIRING_RTS  UART_PIN_NO_CHANGE
#define PAIRING_CTS  UART_PIN_NO_CHANGE
#define PAIR_BUFSIZE (1024)

#else // Production
#define UP_BUTTON   GPIO_NUM_39
#define DOWN_BUTTON GPIO_NUM_36
#define FIRE_BUTTON GPIO_NUM_0

#define UP_GPIO_INPUT   (1ULL << GPIO_NUM_39)
#define DOWN_GPIO_INPUT (1ULL << GPIO_NUM_36)
#define FIRE_GPIO_INPUT (1ULL << GPIO_NUM_0)

#define I2C_SCL  GPIO_NUM_22
#define I2C_SDA  GPIO_NUM_21
#define I2C_SCL2 GPIO_NUM_2
#define I2C_SDA2 GPIO_NUM_16

#define PIN_NUM_TOUCH_CLK  GPIO_NUM_26
#define PIN_NUM_TOUCH_CS   GPIO_NUM_27
#define PIN_NUM_TOUCH_IRQ  GPIO_NUM_32
#define PIN_NUM_TOUCH_MISO GPIO_NUM_35
#define PIN_NUM_TOUCH_MOSI GPIO_NUM_33

#define PIN_NUM_DISPLAY_MISO      GPIO_NUM_19
#define PIN_NUM_DISPLAY_MOSI      GPIO_NUM_23
#define PIN_NUM_DISPLAY_CLK       GPIO_NUM_18
#define PIN_NUM_DISPLAY_CS        GPIO_NUM_17
#define PIN_NUM_DISPLAY_DATA_CMD  GPIO_NUM_4
#define PIN_NUM_DISPLAY_BACKLIGHT NOPIN
#define PIN_NUM_DISPLAY_RESET     NOPIN

#define PAIRING_UART  UART_NUM_2 //FIXME?
#define PAIRING_RX    GPIO_NUM_34
#define PAIRING_TX    GPIO_NUM_25
#define PAIRING_RTS   NOPIN
#define PAIRING_CTS   NOPIN
#define PAIR_BUFSIZE  (1024)
#endif

#endif
